apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: onlinebookstores
  description: Online Bookstores web application
  annotations:
    dynatrace.com/dql-query-definitions: |
      {
        "logs": {
          "displayName": "Laptop Logs",
          "dql": "fetch logs | limit 50"
        }
      }
spec:
  type: service
  owner: Purvash-143
  lifecycle: unknown


