apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: onlinebookstores
  description: Online Bookstores web application
  annotations:
    dynatrace.com/dql-query-definitions: |
      {
        "dynatrace.logs": {
          "displayName": "Laptop Logs",
          "dql": "fetch logs | limit 50",
          "queryId": "logs"
        }
      }
spec:
  type: service
  owner: SonarQube
  lifecycle: production
